### ISSUE TITLE
Use Multiple VPNs

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [TrackerControl/tracker-control-android#141]
Right now, NetGuard is using my only VPN spot; I'd be perfect if tracker-control could HOST a SOCKS5 proxy (like the Orbot app does), so that it could be used in conjuction with NetGuard.
With the right implementation we might even be able to chain the SOCKS5 proxies, and use NetGuard + Tracker-Control + Orbot :D

**Comment by PinkDev1** [comment]
That's correct! but sometimes you're pretty much forced to give a proprietary app internet-access (Credit Card app, most multiplayer online F2P android games, etc)

**Comment by robovoice1** [comment]
Many bank apps have up to 5 in-app tracker libraries (firebase... etc).

**Comment by ItsIgnacioPortal** [comment]
To any privacy enthusiasts who encounter this issue: Since opening this issue, I have adapted my setup to use NetGuard + personalDNSfilter + a VPN.

The benefit of using personalDNSfilter instead of the built-in host blocking of NetGuard, is that I can use much more advanced filter lists (wich support wildcard blocking), AND continue to use DoH or DoT.


No root or self-hosting needed: https://itsignacioportal.github.io/netguard-pdnsf-any-vpn-combo/

**Comment by kasnder** [comment]
> To any privacy enthusiasts who encounter this issue: Since opening this issue, I have adapted my setup to use NetGuard + personalDNSfilter + a VPN.
> 
> The benefit of using personalDNSfilter instead of the built-in host blocking of NetGuard, is that I can use much more advanced filter lists (wich support wildcard blocking), AND continue to use DoH or DoT.
> 
> No root or self-hosting needed: https://itsignacioportal.github.io/netguard-pdnsf-any-vpn-combo/

I love this manual! Thanks for sharing. Should also be compatible with TC.

**Comment by kasnder** [comment]
Also see #61. Someone suggested a similar approach there.

**Comment by kasnder** [comment]
closing this and continuing in the other issue
