### ISSUE TITLE
Hide apps with no internet access toggle

### ISSUE THREAD

**Issue by p2635** [TrackerControl/tracker-control-android#144]
Enhancement request to make it easier to navigate the list. May be nice to have a toggle to hide apps that have no internet access.

**Comment by kasnder** [comment]
Thanks, that's a great suggestion!

**Comment by kasnder** [comment]
Indeed, this used to be part of TC, but I removed it.. my bad.

**Comment by JarlavGrenland** [comment]
> Indeed, this used to be part of TC, but I removed it.. my bad.

Is this feature coming back?
