### ISSUE TITLE
App internet is disabled when monitoring is disabled and always-on is enabled

### ISSUE THREAD

**Issue by p2635** [TrackerControl/tracker-control-android#145]
I tested the disable monitoring feature for Newpipe but it seemed to disable internet access for it. I don't know if this is a bug or just my understanding of how how it should work.

Android 10
TC 20201025 fdroid

Steps to reproduce
Disable monitoring for newpipe

![Screenshot_20201114-163055_TrackerControl](https://user-images.githubusercontent.com/4522927/99152144-d3303080-2697-11eb-9ce1-fabf498dcb80.jpg)

Strict blocking is on but not sure if that is relevant or not

Expected results
Newpipe is not blocked or affected by TC.

Actual results
Newpipe can't load any videos

**Comment by kasnder** [comment]
Thanks for reporting. This is very weird, because disabling of monitoring should allow NewPipe to circumvent the TrackerControl VPN altogether.

**Comment by kasnder** [comment]
I tried this on my device and NewPipe is working fine.

**Comment by kasnder** [comment]
Do you have Always-On VPN or something?

**Comment by p2635** [comment]
@kasnder correct, I turned it on so I have TC running all the time

**Comment by kasnder** [comment]
This causes the issue then!

**Comment by kasnder** [comment]
Not sure if there's much I can do about it actually. Yet, if you disable all categories that should have a similar effect.

**Comment by p2635** [comment]
Yeah there is a workaround but I wanted to report to you, thanks
