### ISSUE TITLE
Grouping of trackers? 

### ISSUE THREAD

**Issue by ja7833** [TrackerControl/tracker-control-android#250]
I've noted that Fingerprinting often appears in more than one group for the same app vs Advertising, Analytics, Essential, Social, and Uncategorised which are always in one group.

Is this by design or should all Fingerprinting be in one group so **Block** can be toggled on/off all at once for an app?  Maybe label as Fingerprinting "hardware specifications" and Fingerprinting "app settings" etc. if they are distinct types of Fingerprinting?

**Comment by ja7833** [comment]
Update.  I've switched to [Bromite](https://github.com/bromite/bromite) from Brave since I opened this issue.  Fingerprinting  (_or any other tracker category_) has **not** created more than one group for Bromite.

**Comment by ja7833** [comment]
Reopening this issue.  Only a few days after closing #250 thinking maybe it was an anomaly with Brave, Bromite now has a second Fingerprinting group with a single entry "m.stripe.network"

**Comment by kasnder** [comment]
I generally don't recommend using TC with browsers though. Bromite already comes with anti-tracking technology, and browser can offer better protection that TC on websites.

**Comment by ja7833** [comment]
Thanks for the update.  

I see as of Version 2022.02.10 a new highlight in the UI was added that browsers are not supported with a recommendation to use a browser like [Bromite](https://www.privacyguides.org/browsers/)) integrated anti-tracking.

**Comment by kasnder** [comment]
> Thanks for the update.
> 
> I see as of Version 2022.02.10 a new highlight in the UI was added that browsers are not supported with a recommendation to use a browser like Bromite with integrated anti-tracking.

Yes! :)
