### ISSUE TITLE
Trackers Listed Twice

### ISSUE THREAD

**Issue by HonestAbe7** [TrackerControl/tracker-control-android#268]
I noticed when clicking on an app that the trackers are listed twice:

![Screenshot_20211218-153714](https://user-images.githubusercontent.com/88217236/146654903-db1793cd-7e21-4576-8f12-1f786ab6c1f0.png)

**Comment by kasnder** [comment]
I'm just as annoyed as you about this proglem, but haven't been able to track down the source of this, since it seems to be device-specific.

**Comment by kasnder** [comment]
The next update will fix this!
