### ISSUE TITLE
Minor errors in Fastlane structure

### ISSUE THREAD

**Issue by IzzySoft** [TrackerControl/tracker-control-android#276]
I've just updated the URLs in the F-Droid metadata, and the bot came up with these:

```
summary in el-GR should be shorter than 80 characters!
es_ES is invalid! Do you mean es-ES?
summary in fr-FR should be shorter than 80 characters!
summary in gl-ES should be shorter than 80 characters!
summary in hu-HU should be shorter than 80 characters!
summary in it-IT should be shorter than 80 characters!
summary in nl-NL should be shorter than 80 characters!
summary in pl-PL should be shorter than 80 characters!
summary in ta-IN should be shorter than 80 characters!
summary in tr-TR should be shorter than 80 characters!
summary in vi-VN should be shorter than 80 characters!
```

Thought you might wish to check. At least the second one should be pretty easy to fix :smile: As for the others: they'll currently be truncated at char 80.

**Comment by kasnder** [comment]
Ooops, thanks for flagging this!

**Comment by kasnder** [comment]
Should be fixed now!

**Comment by IzzySoft** [comment]
And that fast – thanks! With the next release, it will then land at F-Droid (and in my repo; here I could manually trigger a "fastlane refresh" right away if you want but would refrain from it if it already contains changes for the next release).

**Comment by IzzySoft** [comment]
@kasnder uiuiui… sorry for necromancing, but:

* build/net.kollnig.missioncontrol/metadata/en-US/changelogs/2026040301.txt has 1215 chars

That's WAAAYY above the 500 char limit 🙈

**Comment by kasnder** [comment]
> [@kasnder](https://github.com/kasnder) uiuiui… sorry for necromancing, but:
> 
>     * build/net.kollnig.missioncontrol/metadata/en-US/changelogs/2026040301.txt has 1215 chars
> 
> 
> That's WAAAYY above the 500 char limit 🙈

Oops. I didn't realise that there's a limit... I had a bit of time around Christmas to add new stuff...

**Comment by IzzySoft** [comment]
You can even use [this Github action](https://github.com/ashutoshgngwr/validate-fastlane-supply-metadata) to keep watch btw 😉

**Comment by IzzySoft** [comment]
🤗 Thanks!
