### ISSUE TITLE
Cursor Window Allocation Exception on Android 9

### ISSUE THREAD

**Issue by Aledosim** [TrackerControl/tracker-control-android#280]
**Do you use TrackerControl from Google Play/F-Droid/other?**
I'm using the F-Droid version

**Describe the bug**
A few minutes after launching the app, a exception is raised and the internet connection stops. I need to close it on "Apps and notification" panel to retrieve the connection. The exception: 
```android.database.CursorWindowAllocationException: Cursor window allocation of 2097152 bytes failed. # Open Cursors=892 (# cursors opened by this proc=892)```
I'm on a Motorola G6 Play, Android 9

**Comment by kasnder** [comment]
Sorry to hear that, and thanks for reporting! Can you send a full crash report to crash@trackercontrol.org please?

**Comment by Aledosim** [comment]
I changed my cellphone and I am not using TC anymore. Sorry.
