### ISSUE TITLE
Implement a Data Usage Graph and Notification Counter

### ISSUE THREAD

**Issue by MercerBoi** [TrackerControl/tracker-control-android#281]
This app may just be the open-source alternative to Glasswire I've been looking for. The only thing it's missing right now is the functionality to see which apps are using the most data. Implementing such a feature much like what Glasswire does would be really appreciated. Also, it'd be great if it could also indicate the network speed at any given time, in the notification counter.

I realise that this is beyond the purview of the app, but I'm just putting this out there for the developer to consider. It would be really appreciated. Thank you.

**Comment by kasnder** [comment]
Thank you for the recommendation. As far as I'm concerned, most of this functionality is actually implemented by NetGuard, upon which the underlying VPN functionality of TC is based.

Having said that, you might want to give that app, NetGuard, a try.
