### ISSUE TITLE
Same library twice on the list

### ISSUE THREAD

**Issue by olekstomek** [TrackerControl/tracker-control-android#283]
Same library (Google Firebase Analytics) twice on the list - is it correct? 

![IMG_20220127_210140.jpg](https://user-images.githubusercontent.com/26818304/151435084-78eda587-19ee-4527-92a3-0c12b4aef331.jpg)

**Comment by kasnder** [comment]
Should be fixed in the next update!

**Comment by olekstomek** [comment]
The same problem is for: Google AdMob and Google CrashLytics.

**Comment by kasnder** [comment]
Again, super sorry about that! It'll be fixed soon. :)

**Comment by olekstomek** [comment]
Everything's all right. :) I added more details just to clarify the problem.

**Comment by kasnder** [comment]
For reference: https://github.com/TrackerControl/tracker-control-android/commit/5d1d635570da0fe95d2b09ac9052829c6cfbd5b7

And: #268
