### ISSUE TITLE
dns log  

### ISSUE THREAD

**Issue by Tanzin01** [TrackerControl/tracker-control-android#284]
**Do you use TrackerControl from Google Play/F-Droid/other?** 
F-droid (2021.12.09)

**Describe the bug**
Dns log of tc can't detect all connections(netd in this case)

**To Reproduce**
1. Open telegram
2. View log in tc
Repeat this process with [pcapdroid](https://github.com/emanuele-f/PCAPdroid) 

Screenshots-

![Screenshot_20220129-013320](https://user-images.githubusercontent.com/41266558/151611257-fb89c13e-8c76-4403-9853-600d95e49282.png)

![Screenshot_20220129-013150](https://user-images.githubusercontent.com/41266558/151610471-dad437b4-b629-4262-bb8f-f12b408330d7.png)

**Comment by kasnder** [comment]
This seems to be a system app, and I don't offer support for this.

Have you enabled the monitoring of system apps from the TC settings though?

**Comment by Tanzin01** [comment]
yes, monitoring of system apps is enabled.
