### ISSUE TITLE
app's trackers list collapsible

### ISSUE THREAD

**Issue by lucamp** [TrackerControl/tracker-control-android#289]
After months of using TC, my fennec has 86 trackers blocked, most of them are in the "essential" list (such as xxxx-cloudfront.net).
However it happens that I have to manually switch on trackers in the "advertising" list (such as amazon if I want to login in or others if the site need them to work properly), in this case finding them in such a huge lists takes a little bit of time.

**Describe the solution you'd like**
Having every sections collapsible with a plus/minor sign (or an arrow) near its name would help a lot. For instance, if you want to shows trackers' list:

'- Essential'
'+ Fingerprint'
'+ Ad'
'+ Social'
'+ No category'

Thanks

![Screenshot_2022-02-02-15-50-28-81](https://user-images.githubusercontent.com/15078341/152181150-f8583c56-74db-4306-b38b-5f8fd2262340.jpg)

**Comment by kasnder** [comment]
Use of TC with browsers isn't recommended, and I don't actively support it.

In your case, Fennec already provides brilliant tracker blocking solutions, e.g. the uBlock addon.

Such addons can much better address tracking than TC ever could, so I'm not working on this.

The upcoming version of TC will provide more information inside the app itself.

**Comment by lucamp** [comment]
> Such addons can much better address tracking than TC ever could

I always though TC was better than Firefox as a blocking solution, since the main page [https://trackercontrol.org/](https://trackercontrol.org/) states:

> To detect tracking, TrackerControl combines the power of the Disconnect blocklist, used by Firefox, **and our in-house blocklist is used**, created from analysing ~2 000 000 apps! Additionally, TrackerControl supports custom blocklists.

I had always used TC with Energized block basic and Fennec + uBlock Origin with Energized block basic. I know it's redundant, but the second allows me to apply cosmetic filters that remove the spaces left by ads.

If, as an ad blocker, TC is not better than Firefox + ublock with the same blocklist, does this means there are also no differences between TC and [PersonalDNSfilter](https://f-droid.org/en/packages/dnsfilter.android/) with the same custom blocklist?

Could you please explain it better?

**Comment by kasnder** [comment]
TrackerControl is built to block tracking within apps, but not on websites. PersonalDNSfilter is a great tool. Whether one tool is better than the other is a rather personal decision, depending on what you put your preference. TC aims to surface what blocking activities take place within apps, and motivate individuals to engage with these practices. Compared to other tools, it doesn't aim to make the blocking of tracking as easy as possible, because the underlying decisions of what to block are not easy.
