### ISSUE TITLE
Like a tracker blocking app having trackers like whaty

### ISSUE THREAD

**Issue by Raif1** [TrackerControl/tracker-control-android#298]
![tc.png](https://user-images.githubusercontent.com/93464125/159148804-13240887-3bdc-495b-b097-15e1dd2bf094.png)

**Comment by kasnder** [comment]
For reference, it is disclosed in the privacy policy that ACRA is used to show a popup dialog in case of app crashes. TC never does tracking in the background.

More here: <https://github.com/TrackerControl/tracker-control-android#privacy-notice>

**Comment by Raif1** [comment]
I didnt know that actually so after some research i know
