### ISSUE TITLE
itch.io categorized as fingerprinting

### ISSUE THREAD

**Issue by privsecti** [TrackerControl/tracker-control-android#300]
**Do you use TrackerControl from Google Play/F-Droid/other?**
F-Droid

**Describe the bug**
Tried using [Mitch](https://github.com/gardenappl/mitch) and TC blocked [itch.io](https://itch.io) displaying it as fingerprinting - might be a bug? or does itch.io actually do any fingerprinting?

**Comment by kasnder** [comment]
Good question! The following explains why this is the case: https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#itch
