### ISSUE TITLE
msg_waiting is incorrect for Polish language

### ISSUE THREAD

**Issue by olekstomek** [TrackerControl/tracker-control-android#307]
I noticed that the app gives me notifications "Oczekiwanie na imprezę" which in English literally means "Waiting for party".  :)
https://github.com/TrackerControl/tracker-control-android/blob/0892409033076d35845d4465342138d4a03e9117/app/src/main/res/values-pl-rPL/strings.xml#L116

According to the description of this value in English:
`<string name="msg_waiting">Waiting for event</string>`
in Polish language correct is:
`<string name="msg_waiting">Oczekiwanie na zdarzenie</string>`

**Comment by kasnder** [comment]
Thanks for the suggestion, and sorry that TC contained such an issue. I've now fixed this in our translation platform at <https://crowdin.com/project/trackercontrol>. Feel free to use this platform if you should come around further issues.
