### ISSUE TITLE
Show all network traffic instead of just blocked network traffic. 

### ISSUE THREAD

**Issue by prajwal-koirala-0000** [TrackerControl/tracker-control-android#309]
Hello,
Let's start out by saying thank you for this app, I love it.

On the app page where it shows to let the app access internet and determine what to block, it should show all network traffic and than let the user determine what else to block.

Currently it will only show the blocked network traffic, but it should show all of it and let the users decide if they want to block it.

**Comment by prajwal-koirala-0000** [comment]
![Screenshot_20220512-063547](https://user-images.githubusercontent.com/102563715/168052132-9e45e34a-cec8-434d-b231-8c7f4376969c.png)

On this page it doesn't show any api calls bring made to `signal.org` but it should show it there too.

**Comment by kasnder** [comment]
Currently, not all network traffic is shown to reduce battery impact.

You can inspect all network traffic from the Traffic Log. This can be accessed from the app menu.

**Comment by prajwal-koirala-0000** [comment]
I know but from the traffic log u cannot block a site

**Comment by prajwal-koirala-0000** [comment]
This should be added cause it gives the people ability to create customs lists, and contribute to the general global ad blocking networks.

**Comment by prajwal-koirala-0000** [comment]
If I wanted to block `example.com` I would have to create a whole new list and manage my own list vs this feature being added and not needing to create my own lists.
