### ISSUE TITLE
toggle to hide apps without internet access

### ISSUE THREAD

**Issue by LeOS-GSI** [TrackerControl/tracker-control-android#328]
In app overview all apps are shown, apps with and without internet access. That make the overview a bit uncomfortable/confusing, especially when monitoring system apps. 

A toggle to hide all apps without internet access would be very useful and the app overview cleaner, better usable.

**Comment by AnanasPfirsichSaft** [comment]
I definitely second this. A simple change which would really help. Maybe as a search filter like "has_internet:yes"?

**Comment by LeOS-GSI** [comment]
> I definitely second this. A simple change which would really help. Maybe as a search filter like "has_internet:yes"?

It's already implemented in latest version

**Comment by LeOS-GSI** [comment]
> I definitely second this. A simple change which would really help. Maybe as a search filter like "has_internet:yes"?

It's already implemented in latest version
