### ISSUE TITLE
Add tasker integration to turn on and off

### ISSUE THREAD

**Issue by spart0n654** [TrackerControl/tracker-control-android#330]
A simple integration with tasker so you can have a profile trigger turning off the VPN for tracker control and turning it back on. Especially useful with android auto because it doesn't with any VPN turned on and it would automate some clicks for me turning it off for me when it connects automatically

**Comment by kasnder** [comment]
If a third-party app could disable TrackerControl, this would be a security problem. So, I can't implement this. Sorry!

**Comment by abdulisik** [comment]
To chime in on this, many apps create a bridge specifically for Tasker, not for any third-party app. That shouldn't be a security problem, but rather letting power users add new intents/actions using your app (such as the use case above). An example would be how Sleep as Android does it: https://docs.sleep.urbandroid.org/services/tasker_automate.html

**Comment by Bazoogle** [comment]
It's been a year, is this something you're willing to reconsider @kasnder? I really don't think it would be a security risk, even AFWall+ has some tasker integrations. You would only give access to tasker, not any app, and you could create a toggle for it off by default so anyone who wants to use it can. I think being able to toggle specific apps with tasker would be useful in countless situations, given the flexibility. It would open the door to a lot of things for a lot of users

**Comment by kasnder** [comment]
@Bazoogle, thanks for following up. I'm still not convinved by the security implications of such a change.

**Comment by l00kanio** [comment]
Just FYI: Adguard for Android uses password for automation which you have to put in task config in Tasker. 
I temporarily switched to Adguard from TC but 2nd  one works much better in general
