### ISSUE TITLE
How to block Uncategorised partially

### ISSUE THREAD

**Issue by Ygarr** [TrackerControl/tracker-control-android#335]
How to, e.g, allow only blogpost?
![Screenshots_2022-08-27-16-00-38](https://user-images.githubusercontent.com/14309871/187031407-1216b047-8901-46cb-af49-07a6d5a9f9c6.png)

**Comment by abdulisik** [comment]
Advanced Options ⇒ Domain-based Blocking should give you more granular options under companies. It splits up per domain. For example, in your screenshot, it'd separate Google into blogspot and firebaseio, so you can block one and unblock the other.
Please close the issue once you confirm this behavior.
