### ISSUE TITLE
False Positive..?

### ISSUE THREAD

**Issue by ckrkfrnchmn** [TrackerControl/tracker-control-android#337]
TC detected the following tracker libraries: Google CrashLytics and Firebase Analytics from D-Note app.

According to the Android Manifest the app doesn't use internet permission or any other permissions.

https://github.com/MahmoudRH/D_Note/blob/compose/app/src/main/AndroidManifest.xml

**Comment by kasnder** [comment]
I tested this in the latest TC version, in which case I can't even select the app for tracker analysis.

**Comment by kasnder** [comment]
How did you even access this information?

**Comment by ckrkfrnchmn** [comment]
The author sent it to me because I told him it had trackers in it ---- On Sun, 04 Sep 2022 12:52:36 -0400  ***@***.***  wrote ---- How did you even access this information? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: 


  
    
      
        
        
          
            
              
                
                  
                  
                    
                      
                        
                          
                            
                            
                              
                              
                                
                                  
                                    
                                      
                                        DuckDuckGo removed 1 tracker.
                                      
                                    
                                    
                                  
                                
                              
                              
                              
                                
                                  
                                    
                                      
                                        More →
                                      
                                    
                                  
                                
                              
                              
                            
                            
                          
                        
                      
                    
                  
                  
                
              
            
          
        
        
      
    
  


How did you even access this information?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kasnder** [comment]
I'm closing this because I can't reproduce it.
