### ISSUE TITLE
Automatically block internet connection for selected apps running in background

### ISSUE THREAD

**Issue by Franck1421** [TrackerControl/tracker-control-android#338]
It would be great if there was a way to select apps that have to be blocked when not in use, so when the app tries to connect to internet when in background TC blocks its connection, instead, when running in foreground, TC automatically enables its internet connection. I think this feature would be really useful against a lot of apps that want to track you when not using them.

**Comment by kasnder** [comment]
I think this is already part of #89 

It's unfortunately not that easy to implement.
