### ISSUE TITLE
Add option to proxy DNS requests via SOCKS

### ISSUE THREAD

**Issue by jbas23** [TrackerControl/tracker-control-android#356]
**Is your feature request related to a problem? Please describe.**
Currently, DNS is resolved directly, not through the SOCKS5 proxy.  
This causes DNS leaks when chaining with other VPN services.

**Describe the solution you'd like**
I think [the hostname needs to be passed to the SOCKS server without DNS resolution](https://stackoverflow.com/questions/33099569/how-does-sock-5-proxy-ing-of-dns-work-in-browsers).

**Comment by kasnder** [comment]
I think this is covered by tools like Invizible Pro.
