### ISSUE TITLE
Add more specific blocking

### ISSUE THREAD

**Issue by Invictaz** [TrackerControl/tracker-control-android#368]
For now you can only block essential or social but not specific url's within those areas. Please add.

**Comment by kasnder** [comment]
You can already change to domain-based blocking in the settings.

**Comment by Invictaz** [comment]
No this is not true @kasnder 

I cannot block specific urls even with that setting on. Only the whole appsflyer.com domain not the specific wildcards.

![Screenshot_20230320_003208_TrackerControl](https://user-images.githubusercontent.com/20338545/226216706-43d8643d-773d-48e0-ae23-f57100b38db8.jpg)

**Comment by kasnder** [comment]
Sadly, the currently set-up doesn't allow more fine-grained blocking, but I'll keep this issue open.

**Comment by Invictaz** [comment]
Fine grained blocking allows the ads to be blocked but not the data transfer in specific apps. Until they move everything under one subdomain but oh well.

**Comment by Alexandermis** [comment]
This is also one of my most wanted features

**Comment by kasnder** [comment]
It's not possible to implement this though because Android prevents the installation of custom root certificates since Android 7. Pre Android 7, this used to allow the inspection of contacted URLs. This is not possible anymore. Hence, I'm closing this issue because there's nothing I can do.

**Comment by Invictaz** [comment]
Strenge because I have a custom certificate without root on Android 8.

**Comment by ilonachan** [comment]
The root certificate thing may be required to do filtering on the entire URL, but in my use case for example that's completely irrelevant. Like @Invictaz, I have a case where I want anything from `unity3d.com` to be allowed, but everything under `unityads.unity3d.com` to be blocked. So I only need to differentiate subdomains, which the app already does, it just doesn't let me separately block/unblock the two. This is clearly not a technical issue, but an interface issue, and you absolutely should introduce some way to give the user that control @kasnder
