### ISSUE TITLE
please, add a Firewall feature!

### ISSUE THREAD

**Issue by DI555** [TrackerControl/tracker-control-android#371]
**Is your feature request related to a problem? Please describe.**

no firewall in the app((

**Describe the solution you'd like**

as the program already uses local vpn stuff..,
please, add a Firewall feature, with black and/or wite listing modes!
with may be even better than in NG custom settings..
NG has become boring..
would like the Firewall feature be in TC, please!

many thanks in advace!

**Comment by kasnder** [comment]
Thanks for the suggestion. I won't implement this because I'd like to differentiate TC from NG. The NG author has put much effort into developing his app, and I don't just want to free ride. Sorry!
