### ISSUE TITLE
Notification details

### ISSUE THREAD

**Issue by codeXXjs** [TrackerControl/tracker-control-android#372]
Hey I would like to request a feature. 
Enable more info in the notification such as number of blocked and unblock internet connected apps. This has been in netguard and I wish you will add this soon. 
Also more sorting options such as "Sort blocked internet apps" similar to that of netguard. 
Thanks

**Comment by kasnder** [comment]
Thanks for the suggestion. I won't implement this because I'd like to differentiate TC from NG. The NG author has put much effort into developing his app, and I don't just want to free ride. Sorry!
