### ISSUE TITLE
Blocklist

### ISSUE THREAD

**Issue by Kncuk** [TrackerControl/tracker-control-android#373]
**Is your feature request related to a problem? Please describe.**
Release of full blocklist used
Reading the description it appears that TC has an in-house list of trackers, I was wondering about the possibility of releasing such list so one can integrate said list in Pi-Hole
**Describe the solution you'd like**
Release of in-house list

**Comment by landry314** [comment]
i think this means it would be nice to have a blacklist of whitelist of trackers that spans all apps...

**Comment by kasnder** [comment]
It's all in this directory: https://github.com/TrackerControl/tracker-control-android/tree/master/app/src/main/assets
