### ISSUE TITLE
New Category for Crash and Bug Reports

### ISSUE THREAD

**Issue by landry314** [TrackerControl/tracker-control-android#375]
certain sites like:

firebase-settings.crashlytics.com
sessions.bugsnag.com

are for reporting bugs and crashes.

crashlytics is currently in analytics and bugsnag is uncategorized. wouldnt a new category for these type of sites make sense?

**Comment by kasnder** [comment]
Yeah, probably, but the categories are taken from Mozilla Firefox: https://github.com/mozilla-services/shavar-prod-lists

You'd need to file an issue there.
