### ISSUE TITLE
TC doesn't set custom DNS servers

### ISSUE THREAD

**Issue by najjara** [TrackerControl/tracker-control-android#384]
**Do you use TrackerControl from Google Play/F-Droid/other?**
2023.01.31-fdroid

**Describe the bug**
Custom DNS servers are set under Settings > Advanced options > VPN DNS, different from what's set under DHCP.
When TC is on, the specified DNS servers are NOT set and used. Since Android doesn't provide a straightforward way of displaying the set servers, the easiest way of checking is through DNS leak test websites such as dnscheck.tools or dnsleaktest.com

The resolvers show as the ones pushed through DHCP, and not what's been set in TC.
This is an issue whether only 1 or 2 servers are set, only IPv4 or IPv6 servers are used, or a mix of both protocols (one in each field).

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Advanced options'
3. Scroll down to 'VPN DNS'
4. Set a DNS server (e.g. 9.9.9.9 or 1.1.1.1)
5. Go to dnscheck.tools
6. See error (i.e. resolver is NOT 9.9.9.9 or 1.1.1.1 server) (I know that the resolver isn't going to show as the anycast 9.9.9.9 . The result is my ISP for example, what's set by DHCP, and not an IP associated with Quad9 or Cloudflare)

**Comment by kasnder** [comment]
this is an advanced option, and i currently don't have the option to investigate this further. sorry. you can always use an app like nebulo and redirect port 53 to this app so as to enable DoH or DoT

**Comment by najjara** [comment]
It's not fair to mark this "completed". Please change it to WONTFIX.

**Comment by kasnder** [comment]
good point. thanksQ

**Comment by Uneccessary** [comment]
@kasnder 

> this is an advanced option, and i currently don't have the option to investigate this further. sorry.

A warning atleast would be nice, many people do trust this and use it. If they do not check they don't even realize that they still are using the DNS of their ISP or device, this is very misleading. I would completly disable (gray out) this option currently so people don't think it's working. Also I and many other would appriacate it if you coud take some time investigating this, bc since you don't auto-update the StevenBlack Filterlist (and ig the others too) and since adding new additional filterlists is also not a option this was always a great option to optimize the tracking protection.

**Comment by mklopp** [comment]
If you have disabled monitoring on your browser? If yes then it won't use the DNS you set in the Settings. Try enabling the monitoring on your browser but disabling any blocking. You should see that DNS that you set is used

**Comment by Uneccessary** [comment]
Thanks for pointing this out to me, wasn't aware of it, but actually never tested it too which I kinda regret. After enabling monetoring and doing a test with https://dnscheck.tools/ Adguard DNS which I've configured actually showed up as DNS, but also Google and Cloudfare which I hadn't configured nor my WLAN. I will investigate this further with other DNS providers, maybe it's just Adguard rerouting my request? Idk.

**Comment by kasnder** [comment]
The DNS servers are only for backup. By default, the Android DNS servers are used.
