### ISSUE TITLE
Show only apps with internet access

### ISSUE THREAD

**Issue by LeOS-GSI** [TrackerControl/tracker-control-android#388]
Pls show only apps with internet access to get a better overview in app list

**Comment by kasnder** [comment]
thanks for the suggestion! i wonder if users might get confused about why certain apps do not show up in the list?

**Comment by LeOS-GSI** [comment]
I don't think so. In the moment I have integrated the advanced privacy from murena. It has a short explanation above app list, where is written, that only apps with internet are shown.

Or you will make a toast like that one from battery optimizing, or from PrivateDNS with a note, that only apps with internet are shown

**Comment by kasnder** [comment]
The latest version now adds an option to hide apps without internet access.

**Comment by LeOS-GSI** [comment]
> The latest version now adds an option to hide apps without internet access.

but you have not released it :(
