### ISSUE TITLE
Feature to Only Block Trackers on Selected Apps

### ISSUE THREAD

**Issue by petebaker17** [TrackerControl/tracker-control-android#396]
Hi, I don't know if I just can't find the option, but how do I just make it so certain apps are in a blacklist and the trackers are blocked but all other apps aren't affected at all by tracker control?

Is there an easy way to do this?

**Comment by samuelps26** [comment]
Hi, when you hit the toggle "Monitoring" this specific app will be excluded from blocking and analysing trackers. This might be what you're looking for...
