### ISSUE TITLE
TC recommends outdated browser

### ISSUE THREAD

**Issue by hjek** [TrackerControl/tracker-control-android#402]
**Do you use TrackerControl from Google Play/F-Droid/other?**
F-Droid

**Describe the bug**
When looking at a browser in TC, there's a text recommending Bromite and Fennec. Bromite hasn't been updated for a year.

**To Reproduce**
1. Open TC
2. Click on a browser, like Lightning
3. See Bromite recommendation

**Comment by kasnder** [comment]
addressed now!
