### ISSUE TITLE
Duplicate TrackerControl application page on F-Droid

### ISSUE THREAD

**Issue by Korb** [TrackerControl/tracker-control-android#411]
On F-Droid I see two applications that at first glance appear to be the same:

TrackerControl (monitor and control hidden data collection in mobile apps)
https://f-droid.org/packages/net.kollnig.missioncontrol/

TrackerControl (TrackerControl allows to monitor and control hidden data collection in apps.)
https://f-droid.org/packages/net.kollnig.missioncontrol.fdroid/

README.md provides a link to the second one. Do I need to request the removal of the first application as a fake?

**Comment by kasnder** [comment]
The first link does not even work for me. It also should not work. The second link is the one that I maintain.

**Comment by kasnder** [comment]
Do you happen to have multiple repos though, e.g. the IzzyOnDroid repo?

**Comment by Korb** [comment]
> Do you happen to have multiple repos though, e.g. the IzzyOnDroid repo?

Yes, I have several repositories. About a hundred, probably.

**Comment by licaon-kter** [comment]
the client can't (yet; WiP: https://gitlab.com/fdroid/wiki/-/wikis/Repository-Management-Overhaul/Representing-apps-from-multiple-repos) offer the Link to the correct repo. You can Expand Versions and see the repo name today.

first link should be https://android.izzysoft.de/repo/apk/net.kollnig.missioncontrol I guess

/close as invalid
