### ISSUE TITLE
Add a sort option for "most recently used"

### ISSUE THREAD

**Issue by Cris-Edmundson** [TrackerControl/tracker-control-android#421]
**Reason**
Tracker control requires a fair bit of fine tuning if you wanna block as much as possible and still have things work. I frequently open the tracker control app because something I was trying to do elsewhere wasn't working and I need to try troubleshooting with TC. But it takes a minute to find the app I was trying to use, which adds additional friction to what's already an inconvenience.

**Request**
It'd be super helpful if I could sort the list such that the most recently used apps were at the top, so as soon as I open tracker control I can change settings for the app I was trying to use

This might require usage access (or I guess you could probably implement it using network traffic, but that seems like it makes less sense) but I think it would really improve the UX of the app and reduce the inconvenience created by filtering your devices network traffic

Really love the app, thanks to all the folks who have worked on it :)

**Comment by kasnder** [comment]
Would be really cool indeed but I don't have access to what apps were last used. Sorry!
