### ISSUE TITLE
Monitored apps don't work on mobile data

### ISSUE THREAD

**Issue by Skarfester** [TrackerControl/tracker-control-android#422]
**Do you use TrackerControl from Google Play/F-Droid/other?**
2024.01.03-fdroid, android 11.

**Describe the bug**
Hello,
On wifi everything works as expected but when I'm on mobile data any of the monitored apps work (they report to be offline). If I stop monitoring that app or pause TrackerControl the app works again. All the other non monitored apps work.
While using any of those monitored apps nothing appears on the traffic log, like it is not even trying to connect. Another user reported a similar behavior on issue [#297](https://github.com/TrackerControl/tracker-control-android/issues/297).
I wonder if there is any setting to solve this that I don't know off. I tried changing all network options without success.
Thank you very much for your support.

**To Reproduce**
1. Turn off wifi and open any monitored app using mobile data (doesn't work).
2. Stop monitoring that app or pause TrackerControl (now it works).

**Comment by Skarfester** [comment]
Hello,
After introducing some DNS addresses in the advanced options settings all monitored apps work on mobile data.
So apparently this solves the issue.

**Comment by acress1** [comment]
Hi @Skarfester, can you explain how you solved the problem ?
I've got the same.
Thanks,
cress

**Comment by Skarfester** [comment]
Hi @acress1 , sorry for the delay.
As I said in my previous message, going to _> Settings > Advanced options_ and filling both _VPN DNS_ addresses solved the problem for me.

**Comment by acress1** [comment]
No worries. Ok thank you, I will give it a try.

Cress
