### ISSUE TITLE
Block all connections not using VPN feature

### ISSUE THREAD

**Issue by fdawans** [TrackerControl/tracker-control-android#427]
**Do you use TrackerControl from Google Play/F-Droid/other?**
TrackerControl 2024.01.03-fdroid

**Describe the bug**
I would like to have all connections not going through the VPN to be blocked but this feature blocks some apps from the internet. 
I believe this feature can be useful in case TC crashes or doesn't start after a reboot. 

**To Reproduce**
1. Go to phone settings > VPN > TrackerControl
2. Click on i icon (information) 
3. Enable "block all connections not using VPN option
4. Some apps cannot connect to the internet (is this expected?

**Comment by kasnder** [comment]
Yes, this is expected. Don't use that option.
