### ISSUE TITLE
Outdated detection of tracker libraries

### ISSUE THREAD

**Issue by ja7833** [TrackerControl/tracker-control-android#437]
**Do you use TrackerControl from Google Play/F-Droid/other?**
Android 15. TC v2024.01.02 provided by IzzyOnDroid F-Droid Repo.

Describe the bug
Detected tracker libraries: None

**Describe the bug**
The developer of an F-Droid app I use added https://www.acra.ch/ for opt-in crash reporting several months ago.

While https://exodus-privacy.eu.org/en/ and https://f-droid.org/en/packages/org.eu.exodus_privacy.exodusprivacy/ correctly show this tracker in the app, TC shows "Detected tracker libraries: None."

**Comment by kasnder** [comment]
TC uses ACRA, too. Yet, ACRA isn't necessarily a tracker in terms of the definition used by TC.
